import { Product } from "@/types/product";

export const SAMPLE_PRODUCTS: Product[] = [
  {
    id: "prod-1",
    title: "Körpə üçün Pambıq Bodi Dəsti (3-lü)",
    description: "100% təbii pambıqdan hazırlanmış, nəfəs alan və körpə dərisi üçün tam təhlükəsiz 3 ədədli bodi dəsti. Rahat düyməli bağlanış.",
    price: 24.90,
    original_price: 35.00,
    age_category: "0-2",
    gender: "Unisex",
    image_url: "https://images.unsplash.com/photo-1522771930-78848d9293e8?w=800&auto=format&fit=crop&q=80",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
  },
  {
    id: "prod-2",
    title: "Çiçək Naxışlı Zərif Yay Donu",
    description: "Yumşaq pambıq astarı olan, çiçək motivləri ilə bəzədilmiş qız uşağı üçün zərif yay donu. Bayram və gündəlik üçün idealdır.",
    price: 34.00,
    original_price: 48.00,
    age_category: "3-5",
    gender: "Girl",
    image_url: "https://images.unsplash.com/photo-1622290291468-a28f7a7dc6a8?w=800&auto=format&fit=crop&q=80",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 4).toISOString(),
  },
  {
    id: "prod-3",
    title: "Klassik Cins Gödəkçə və Şalvar Dəsti",
    description: "Davamlı denim parça, rahat kəsim və müasir dizayn. 6-12 yaş oğlan uşaqları üçün aktiv hərəkətə uyğundur.",
    price: 49.00,
    original_price: 65.00,
    age_category: "6-12",
    gender: "Boy",
    image_url: "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&auto=format&fit=crop&q=80",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 3).toISOString(),
  },
  {
    id: "prod-4",
    title: "Yumşaq Toxunma Qış Jaketi (Kardigan)",
    description: "Hipoalergenik yun qarışıqlı iplikdən toxunmuş isti jaket. Payız və qış fəsillərində körpənizi isti və rahat saxlayır.",
    price: 29.00,
    original_price: 39.00,
    age_category: "0-2",
    gender: "Unisex",
    image_url: "https://images.unsplash.com/photo-1519457431-44ccd64a579b?w=800&auto=format&fit=crop&q=80",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
  },
  {
    id: "prod-5",
    title: "Sport Stil Kapüşonlu Hudi və İdman Şalvarı",
    description: "İkiqat pambıq parçadan hazırlanmış dəbli idman dəsti. Uşaqlar üçün ən sevimli və rahat gündəlik seçim.",
    price: 39.00,
    original_price: 55.00,
    age_category: "3-5",
    gender: "Boy",
    image_url: "https://images.unsplash.com/photo-1503919545889-aef636e10ad4?w=800&auto=format&fit=crop&q=80",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
  },
  {
    id: "prod-6",
    title: "Tül Ətəkli Şənlik Donu",
    description: "Qızlar üçün ad günü və xüsusi günlər üçün nəzərdə tutulmuş parıltılı və pambıq astarlı təntənəli libas.",
    price: 49.00,
    original_price: 70.00,
    age_category: "6-12",
    gender: "Girl",
    image_url: "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800&auto=format&fit=crop&q=80",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    id: "prod-7",
    title: "Yeniyetmə Oversize Hudi və Kargo Şalvar",
    description: "13-18 yaş yeniyetmələr üçün müasir küçə tərzi (streetwear) pambıq oversize hudi və rahat kargo şalvar dəsti.",
    price: 59.00,
    original_price: 85.00,
    age_category: "13-18",
    gender: "Boy",
    image_url: "https://images.unsplash.com/photo-1509967419530-da38b4704bc6?w=800&auto=format&fit=crop&q=80",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    id: "prod-8",
    title: "Gənc Qızlar üçün Dəbli Cins Gödəkçə Dəsti",
    description: "13-18 yaş üçün premium keyfiyyətli kətan və denim parçadan tikilmiş dəbli geyim dəsti. Tənzimlənən kəmərli.",
    price: 64.00,
    original_price: 89.00,
    age_category: "13-18",
    gender: "Girl",
    image_url: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&auto=format&fit=crop&q=80",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
];
