name: Supabase Keep-Alive

on:
  schedule:
    - cron: '0 0 * * 2,5'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          curl -X GET "${{ secrets.https://ayiomktsbtghlhxgigau.supabase.co }}/rest/v1/products?select=id&limit=1" \
          -H "apikey: ${{ secrets.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5aW9ta3RzYnRnaGxoeGdpZ2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA3OTQ3NzYsImV4cCI6MjEwNjM3MDc3Nn0.ngjSd1Z7GoDn3o597z9VWD0x3LsHlw217fRmIJFoKss }}" \
          -H "Authorization: Bearer ${{ secrets.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF5aW9ta3RzYnRnaGxoeGdpZ2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA3OTQ3NzYsImV4cCI6MjEwNjM3MDc3Nn0.ngjSd1Z7GoDn3o597z9VWD0x3LsHlw217fRmIJFoKss }}"
